# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'iOSExample' do
  pod 'Alamofire'
end

target 'LoggieAlamofire' do
  pod 'Alamofire'
end
