platform :ios, '10.0'
use_frameworks!

target 'Loggie_Example' do
  pod 'Loggie', :path => '../../'
  pod 'Loggie/LoggieAlamofire', :path => '../../'
  pod 'Loggie/URLSession', :path => '../../'
end

target 'Loggie_Tests' do
  pod 'Loggie', :path => '../../'
  pod 'Loggie/LoggieAlamofire', :path => '../../'
  pod 'Loggie/URLSession', :path => '../../'
end

class Pod::Target::BuildSettings::AggregateTargetSettings
    alias_method :ld_runpath_search_paths_original, :ld_runpath_search_paths

    def ld_runpath_search_paths
        return ld_runpath_search_paths_original unless configuration_name == "Debug"
        return (ld_runpath_search_paths_original || []) + (framework_search_paths || [])
    end
end

class Pod::Target::BuildSettings::PodTargetSettings
    alias_method :ld_runpath_search_paths_original, :ld_runpath_search_paths

    def ld_runpath_search_paths
        return (ld_runpath_search_paths_original || []) + (framework_search_paths || [])
    end
end
