platform :ios, '10.0'
use_frameworks!

target 'Loggie_Example' do
  pod 'Loggie', :path => '../../'
  pod 'Loggie/Alamofire', :path => '../../'
end

target 'Loggie_Tests' do
  pod 'Loggie', :path => '../../'
  pod 'Loggie/Alamofire', :path => '../../'
end